// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// match_sequences
Rcpp::DataFrame match_sequences(Rcpp::NumericMatrix short_input, Rcpp::NumericMatrix long_input);
RcppExport SEXP _phyloschuyler_match_sequences(SEXP short_inputSEXP, SEXP long_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type short_input(short_inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type long_input(long_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(match_sequences(short_input, long_input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phyloschuyler_match_sequences", (DL_FUNC) &_phyloschuyler_match_sequences, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_phyloschuyler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
