# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @author Schuyler D. Smith
#' @title Co-occurrence calculation
#' @description Calculate the pair-wise Spearman rank correlation.
#' @param otu_table An \code{otu_table} in the format from \code{\link[phyloseq:otu_table]{phyloseq}}
#' @param treatment_indices A \code{list} with c++ indices for the \code{treatment_names} corresponding to which treatment each column in the \code{otu_table} belongs to.
#' @param treatment_names A \code{Vector} containing the treatment names corresponding to the \code{treatment_indices}.
#' @param p_cutoff \code{double} representing the maximum \code{p-value} accepted for the correlation to be returned.
#' @param ncores \code{int} for how many cores to use to multithread the calculations.
#' @return A \code{data.frame} with treatment, otu_1, otu_2, rho, p values.
#' @seealso \code{\link{co_occurrence}}
co_occurrence_Rcpp <- function(otu_table, treatment_indices, treatment_names, p_cutoff, ncores) {
    .Call('_phylosmith_co_occurrence_Rcpp', PACKAGE = 'phylosmith', otu_table, treatment_indices, treatment_names, p_cutoff, ncores)
}

#' @author Schuyler D. Smith
#' @title Co-occurrence rho calculations
#' @description Calculates the pair-wise Spearman rank correlation without testing for significance.
#' @param otu_table An \code{otu_table} in the format from \code{\link[phyloseq:otu_table]{phyloseq}}
#' @param treatment_indices A \code{list} with c++ indices for the \code{treatment_names} corresponding to which treatment each column in the \code{otu_table} belongs to.
#' @param treatment_names A \code{Vector} containing the treatment names corresponding to the \code{treatment_indices}.
#' @param ncores \code{int} for how many cores to use to multithread the calculations.
#' @return A \code{vector} with rho values for each pair-wise correlation.
#' @seealso \code{\link{permute_rho}}
co_occurrence_rho_Rcpp <- function(otu_table, treatment_indices, treatment_names, ncores) {
    .Call('_phylosmith_co_occurrence_rho_Rcpp', PACKAGE = 'phylosmith', otu_table, treatment_indices, treatment_names, ncores)
}

#' @author Schuyler D. Smith
#' @title Arrange co-occurence table
#' @description Arranges the co-occurence table so that taxa of interest are on the left.
#' @param co_occurrence_table A \code{data.frame} in the format from \code{\link{co_occurrence}}.
#' @param taxa_of_interest A \code{vector} containing names of taxa to be found in either OTU_1 or OTU_2.
#' @return A \code{data.frame} with treatment, otu_1, otu_2, rho, p values.
#' @seealso \code{\link{co_occurrence}}
arrange_co_occurrence_table <- function(co_occurrence_table, taxa_of_interest) {
    .Call('_phylosmith_arrange_co_occurrence_table', PACKAGE = 'phylosmith', co_occurrence_table, taxa_of_interest)
}

match_sequences <- function(short_input, long_input) {
    .Call('_phylosmith_match_sequences', PACKAGE = 'phylosmith', short_input, long_input)
}

